version: '3.8'

services:
  server:
    build:
      context: .
      args:
        MYSQL_USER: laminar
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
        MYSQL_URL: jdbc:mysql://mysql:3306/laminar?useSSL=false&allowPublicKeyRetrieval=true
        EXECUTION_URL: ${LAMINAR_EXECUTION_URL:-host.docker.internal}
        EXECUTION_PORT: ${LAMINAR_EXECUTION_PORT:-5000}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/laminar?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: laminar
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - ${LAMINAR_SERVER_PORT:-8080}:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laminar-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laminar
      MYSQL_USER: laminar
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    volumes:
      - laminar-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laminar-network

volumes:
  laminar-db:

networks:
  laminar-network:
    driver: bridge

